# Dependencies
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            泽洛
tagline:          ']'
description:      'A.K.A Brook Zero, 一枚长脸怪.'
url:              http://hyde.getpoole.com

author:
  name:           Brook Zero
  url:            http://brookzero.com

paginate:         99

# Custom vars
version:          1

github:
  repo:           https://github.com/brookzero