# Site settings
title: CMDR BROOK ZERO
email: me@brookzero.com
url: http://brookzero.com/
description: "I am CMDR Brook Zero, Lorem ipsum dolor sit amet, posse utinam accusata eu mea, cum te laoreet antiopam tincidunt, id verear forensibus vix. Ex omittam dissentiunt qui, sed impetus appetere ad. Purto clita vis ad, sea eu commodo appellantur. Nec tantas aliquam at. Quo ea labore atomorum, usu id minim placerat, no meliore constituto quo.An vel libris explicari constituam. Quo modo luptatum ex, legendos platonem an has. Esse ocurreret te eos, homero mollis eam no, exerci utroque necessitatibus vix no. Eruditi temporibus nec ut.."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: CMDR BROOK ZERO


# Build settings
markdown: kramdown
permalink: pretty
