# Site settings
title: 
email: me@brookzero.com
url: http://brookzero.com/
description: "I am CMDR Brook Zero, Lorem ipsum dolor sit amet, posse utinam accusata eu mea, cum te laoreet antiopam tincidunt."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: CMDR BROOK ZERO


# Build settings
markdown: kramdown
permalink: pretty
