# Dependencies
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Brook 泽洛
tagline:          ']'
description:      '隙中窥月, 凿壁借光, 管中窥豹, 可见一斑.'
url:              http://hyde.getpoole.com

author:
  name:           Brook Zero
  url:            http://brookzero.com

paginate:         99

# Custom vars
version:          1

github:
  repo:           https://github.com/brookzero